def get_map_key(category, lang_key):
    return lang_key if lang_key not in ["puml", "mermaid"] else category


selected_categories = {
    "circuit": ["spice"],
    "hdl": ["verilog"],
    "logic": ["logic_bool"],
    "quantum": ["qasm"],
    "tree": ["newick"],
    "dna": ["fasta", "vienna"],
    "mol": ["smiles", "smarts_react"],
    "neural": ["nn_keras", "nn_onnx_graph"],
    "chess": ["fen"],
    "music": ["abc", "xml"],
    "class": ["puml"],
    "sequence": ["puml"],
    "activity": ["mermaid"],
    "component": ["puml"],
    "state": ["puml"],
    "bpmn": ["bpmn"],
    "gantt": ["mermaid"],
    "sql": ["dbml"],
    "mind": ["mermaid"],
    "kg": ["rdf_xml"],
}
selected_categories_less = {
    "circuit": ["spice"],
    "hdl": ["verilog"],
    "logic": ["logic_bool"],
    "quantum": ["qasm"],
    "tree": ["newick"],
    "dna": ["fasta", "vienna"],
    "mol": ["smiles", "smarts_react"],
    "neural": ["nn_onnx_graph"],
    "chess": ["fen"],
    "music": ["abc"],
    "class": ["puml"],
    "sequence": ["puml"],
    "bpmn": ["bpmn"],
    "gantt": ["mermaid"],
    "sql": ["dbml"],
    "mind": ["mermaid"],
    "kg": ["rdf_xml"],
    "chart": ["plotly"],
    "table": ["plotly"],
}

map_domain = {
    "spice": "electrical",
    "verilog": "electrical",
    "logic_symb": "electrical",
    "logic_bool": "electrical",
    "qasm": "electrical",
    "newick": "biology",
    "vienna": "biology",
    "fasta": "biology",
    "smiles": "chemistry",
    "smarts_react": "chemistry",
    "nn_keras": "computer",
    "nn_onnx_graph": "computer",
    "fen": "art",
    "abc": "art",
    "xml": "art",
    "class": "system",
    "sequence": "system",
    "activity": "system",
    "component": "system",
    "bpmn": "business",
    "gantt": "business",
    "mind": "business",
    "dbml": "system",
    "scxml": "system",
    "state": "system",
    "rdf_xml": "computer",
}

question_templates = {
    "spice": [
        "How many {component} are there in this circuit?",
        "Count the {component} in this circuit.",
        "What is the total number of {component} in the schematic?",
        "How many {component} can you identify in this circuit diagram?",
        "Please tell me the number of {component} present in the circuit.",
        "How many {component} are shown in this circuit layout?",
        "What is the count of {component} in the given circuit?",
        "How many distinct {component} are included in this circuit?",
        "Identify how many {component} appear in the schematic.",
        "How many {component} exist in this circuit representation?",
    ],
    "verilog": [
        "How many {component} are there in this digital circuit?",
        "Count the {component} in this digital design.",
        "What is the number of {component} in the circuit?",
        "How many {component} can be seen in this digital schematic?",
        "Tell me how many {component} exist in this circuit.",
        "How many {component} does the digital design contain?",
        "What is the total {component} count in the model?",
        "Please count the {component} in this design.",
        "How many {component} are visible in the schematic?",
        "What is the number of distinct {component} in this circuit?",
    ],
    "logic_bool": [
        "How many {component} gates are in this circuit?",
        "Count the number of {component} gates present.",
        "What is the total number of {component} gates?",
        "How many {component} gates can you see in this logic diagram?",
        "Please tell me the number of {component} gates in the circuit.",
        "How many distinct {component} gates are included?",
        "Identify how many {component} gates appear in the circuit.",
        "What is the count of {component} gates here?",
        "How many {component} gates are drawn in the diagram?",
        "Total up the number of {component} gates in this schematic.",
    ],
    "qasm": [
        "How many {component} are there in this quantum circuit?",
        "Count the {component} used in this quantum diagram.",
        "What is the total number of {component} in the QASM circuit?",
        "Please tell me how many {component} are present here.",
        "How many distinct {component} are in this quantum schematic?",
        "Identify the number of {component} in this quantum circuit.",
        "What is the count of {component} in this circuit?",
        "How many {component} can you see in the QASM representation?",
        "Give me the number of {component} in this diagram.",
        "How many {component} appear in the quantum circuit design?",
    ],
    "newick": [
        "How many {component} are there in this phylogenetic tree?",
        "Count the {component} in this evolutionary tree.",
        "What is the number of {component} shown in the tree?",
        "How many {component} nodes are present in the phylogenetic diagram?",
        "Identify how many {component} are in this tree representation.",
        "Please count the {component} in the tree.",
        "What is the total {component} count in this phylogenetic structure?",
        "How many distinct {component} are part of the tree?",
        "Tell me how many {component} exist in this evolutionary tree.",
        "What is the number of {component} visible in this tree diagram?",
    ],
    "vienna": [
        "How many '{component}' bases does this secondary structure contain?",
        "Count the '{component}' bases in this RNA structure.",
        "What is the number of '{component}' bases here?",
        "Please identify how many '{component}' bases are present.",
        "How many '{component}' bases appear in this secondary structure?",
        "Tell me the count of '{component}' bases in this diagram.",
        "What is the total '{component}' base count here?",
        "How many '{component}' bases are in the given representation?",
        "Identify the number of '{component}' bases in the structure.",
        "How many '{component}' bases can be observed here?",
    ],
    "fasta": [
        "How many '{component}' bases do these sequences contain?",
        "Count the '{component}' bases across the sequences.",
        "What is the total number of '{component}' bases in this FASTA file?",
        "How many '{component}' bases can be found in these sequences?",
        "Please tell me the count of '{component}' bases.",
        "What is the '{component}' base count across the visualization?",
        "Identify how many '{component}' bases are represented.",
        "How many '{component}' bases exist in these sequences?",
        "Give me the number of '{component}' bases shown here.",
        "What is the count of '{component}' bases present?",
    ],
    "fasta_seq": [
        "How many sequences are there in this logo?",
        "Count the sequences in this FASTA logo.",
        "What is the number of sequences represented?",
        "Please tell me how many sequences appear in this logo.",
        "How many sequences are displayed here?",
        "Identify the number of sequences in the visualization.",
        "What is the total sequence count in this diagram?",
        "How many sequences can you see in the logo?",
        "Give me the number of sequences shown.",
        "What is the count of sequences present here?",
    ],
    "smiles": [
        "How many {component} does this molecule contain?",
        "What is the number of {component} in this molecule?",
        "Count the {component} present in this molecule.",
        "Please tell me how many {component} are in this molecule.",
        "How many distinct {component} can be found in this molecule?",
        "What is the total count of {component} in the molecule?",
        "Identify how many {component} are part of this molecule.",
        "How many {component} exist in this molecular structure?",
        "Give me the number of {component} included in this molecule.",
        "What is the count of {component} represented in this molecule?",
    ],
    "nn_keras": [
        "How many {component} layers are there in this neural network?",
        "Count the {component} layers in this model.",
        "What is the number of {component} layers represented?",
        "Please identify how many {component} layers exist here.",
        "How many {component} layers are in the diagram?",
        "Tell me the count of {component} layers in this network.",
        "What is the total number of {component} layers shown?",
        "Identify how many {component} layers appear in this network.",
        "Give me the number of {component} layers present.",
        "How many {component} layers are visible in this architecture?",
    ],
    "nn_onnx_graph": [
        "How many {component} layers are there in this neural network?",
        "Count the {component} layers in the graph.",
        "What is the number of {component} layers shown?",
        "Please tell me how many {component} layers exist in the network.",
        "How many {component} layers are represented in this diagram?",
        "Identify the count of {component} layers in the network.",
        "What is the total {component} layer count here?",
        "How many {component} layers can you see in the graph?",
        "Give me the number of {component} layers in this structure.",
        "What is the count of {component} layers present?",
    ],
    "fen": [
        "How many {component} are there on this chess board?",
        "Count the {component} pieces in this position.",
        "What is the number of {component} shown on the board?",
        "Please tell me how many {component} are in this setup.",
        "How many {component} can be identified on this chessboard?",
        "What is the total count of {component} in this board position?",
        "Identify the number of {component} pieces shown here.",
        "How many {component} pieces are present in this game state?",
        "Give me the number of {component} in the chess diagram.",
        "What is the count of {component} in this configuration?",
    ],
    "abc": [
        "How many '{component}' notes does this piece of music contain?",
        "Count the '{component}' notes in this visualization.",
        "What is the total number of '{component}' notes shown?",
        "Please tell me how many '{component}' notes appear in the score.",
        "How many '{component}' notes can you see in this music?",
        "Identify the number of '{component}' notes in the piece.",
        "What is the '{component}' note count in this composition?",
        "How many '{component}' notes are written in this notation?",
        "Give me the number of '{component}' notes here.",
        "What is the count of '{component}' notes represented?",
    ],
    "uml": [
        "How many {component} are there in this diagram?",
        "How many {component} appear in the diagram?",
        "How many {component} appear in this representation?",
        "How many {component} can you see in this chart?",
        "How many {component} can you find in this representation?",
        "How many {component} exist in this diagram?",
        "How many {component} are shown in this diagram?",
        "How many {component} are present in this diagram?",
        "Please identify how many {component} are included.",
        "Please identify how many {component} appear here.",
        "What is the total number of {component} shown?",
        "What is the total number of {component} represented?",
        "What is the total number of {component} displayed?",
        "Please tell me how many {component} exist here.",
        "Please tell me how many {component} appear.",
        "Please tell me how many {component} are present.",
        "Identify the number of {component} in this diagram.",
        "Identify the number of {component} included.",
        "Identify the number of {component} shown here.",
        "What is the count of {component} represented here?",
        "What is the count of {component} in this diagram?",
        "Give me the number of {component} included here.",
        "Give me the number of {component} shown.",
        "Give me the number of {component} in the diagram.",
        "Give me the number of {component} present.",
        "What is the number of distinct {component} in the diagram?",
        "What is the number of {component} shown?",
        "What is the number of {component} represented here?",
        "What is the {component} count in this diagram?",
        "Tell me the number of {component} present.",
        "Tell me the count of {component} present.",
        "Count the {component} in the diagram.",
    ],
    "gantt": [
        "How many {component} does this Gantt diagram contain?",
        "Count the {component} in this project timeline.",
        "What is the number of {component} shown in the Gantt chart?",
        "Please identify how many {component} exist here.",
        "How many {component} appear in this timeline?",
        "Tell me the count of {component} tasks in this chart.",
        "What is the total number of {component} displayed?",
        "How many {component} can you see in this Gantt chart?",
        "Give me the number of {component} included.",
        "What is the {component} count here?",
    ],
    "mind": [
        "How many {component}, without root node, has this mind map?",
        "Count the {component} excluding the root node.",
        "What is the total number of {component} in this map without root node?",
        "Please tell me how many {component} are present, excluding the root.",
        "How many {component} appear in this mind map (excluding root)?",
        "Identify the number of {component} nodes without counting root.",
        "What is the {component} count, ignoring the root node?",
        "How many {component} does the mind map contain apart from the root?",
        "Give me the number of {component} excluding root.",
        "What is the number of {component} shown here without root node?",
    ],
    "dbml": [
        "How many {component} are there in the database?",
        "Count the {component} in this diagram.",
        "What is the total number of {component} defined?",
        "Please tell me how many {component} exist in the schema.",
        "How many {component} appear in this model?",
        "Identify the number of {component} present in the database design.",
        "What is the {component} count shown in the schema?",
        "How many {component} can you see in the diagram?",
        "Give me the number of {component} included here.",
        "What is the number of {component} represented in this schema?",
    ],
    "rdf_xml": [
        "How many {component} does this knowledge graph contain?",
        "Count the {component} in this graph.",
        "What is the number of {component} in this KG?",
        "Please identify how many {component} exist in the graph.",
        "How many {component} appear in the visualization?",
        "Tell me the {component} count in this knowledge graph.",
        "What is the total number of {component} shown?",
        "How many {component} can you see in this graph?",
        "Give me the number of {component} represented here.",
        "What is the number of {component} included in the KG?",
    ],
}
