engine:
  model: Qwen/Qwen3-235B-A22B-Instruct-2507
  trust_remote_code: True
  max_model_len: 8192
  max_num_seqs: 256
  tensor_parallel_size: 8
  enable_expert_parallel: True
  gpu_memory_utilization: 0.95
  enforce_eager: True

sampling:
  temperature: 0.6
  top_p: 0.95
  max_tokens: 8192

